# Form implementation generated from reading ui file 'd:\IDE_prj\project_KnowledgeBase\test_QT_Inteface\test_messenger.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBodyContainer = QtWidgets.QWidget(self.centralwidget)
        self.leftBodyContainer.setObjectName("leftBodyContainer")
        self.horizontalLayout.addWidget(self.leftBodyContainer)
        self.rightBodyContainer = QtWidgets.QWidget(self.centralwidget)
        self.rightBodyContainer.setObjectName("rightBodyContainer")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightBodyContainer)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.rightBodyContainer)
        self.frame.setStyleSheet("QLabel{\n"
"border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("background-color: #d9fdd3;")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.rightBodyContainer)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_2.addWidget(self.verticalScrollBar)
        self.horizontalLayout.addWidget(self.rightBodyContainer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>I will display A B C</p><p>I will display A B C </p><p><span style=\" font-size:xx-large; font-weight:600;\">Sized Emojis</span></p><p><span style=\" font-size:48px; color:#000000;\">😀 😄 😍</span></p><p><span style=\" font-size:48px; color:#000000;\"> 💗 ☝🏿 Dark </span></p></body></html>"))
